export const API_ENDPOINTS = {
  buildings: '/api/facilities/buildings',
  rooms: '/api/facilities/rooms',
  students: '/api/people/students',
  registrations: '/api/operations/registrations',
  contracts: '/api/operations/contracts',
  utilities: '/api/operations/utilities',
  roomFeeProfiles: '/api/operations/room-fee-profiles',
  roomFinances: '/api/operations/room-finances',
  invoices: '/api/operations/invoices',
  roles: '/api/people/roles',
  users: '/api/people/users',
}

export const NAVIGATION = [
  { key: 'overview', label: 'Tổng quan' },
  { key: 'operations', label: 'Điều phối phòng' },
  { key: 'facilities', label: 'Cơ sở vật chất' },
  { key: 'students', label: 'Sinh viên' },
  { key: 'finance', label: 'Tài chính' },
  { key: 'admin', label: 'Quản trị' },
]

export const VALUE_LABELS = {
  Male: 'Nam',
  Female: 'Nữ',
  Mixed: 'Hỗn hợp',
  Standard: 'Tiêu chuẩn',
  Premium: 'Cao cấp',
  Available: 'Còn trống',
  Occupied: 'Đang sử dụng',
  Full: 'Đã đầy',
  Maintenance: 'Bảo trì',
  Active: 'Hiệu lực',
  PendingMoveIn: 'Chờ nhận phòng',
  Waiting: 'Chờ xếp phòng',
  Inactive: 'Ngừng ở',
  Pending: 'Chờ duyệt',
  Approved: 'Đã duyệt',
  Rejected: 'Từ chối',
  Expired: 'Hết hạn',
  Cancelled: 'Đã hủy',
  Unpaid: 'Chưa thanh toán',
  Paid: 'Đã thanh toán',
  PartiallyPaid: 'Thanh toán một phần',
  Late: 'Quá hạn',
  Cash: 'Tiền mặt',
  Transfer: 'Chuyển khoản',
  Other: 'Khác',
}

export const GENDER_POLICY_OPTIONS = [
  { value: 'Male', label: 'Khu nam' },
  { value: 'Female', label: 'Khu nữ' },
  { value: 'Mixed', label: 'Khu hỗn hợp' },
]

export const ROOM_TYPE_OPTIONS = [
  { value: 'Standard', label: 'Tiêu chuẩn' },
  { value: 'Premium', label: 'Cao cấp' },
  { value: 'VIP', label: 'VIP' },
]

export const ROOM_STATUS_OPTIONS = [
  { value: 'Available', label: 'Còn trống' },
  { value: 'Occupied', label: 'Đang sử dụng' },
  { value: 'Full', label: 'Đã đầy' },
  { value: 'Maintenance', label: 'Bảo trì' },
]

export const GENDER_OPTIONS = [
  { value: 'Male', label: 'Nam' },
  { value: 'Female', label: 'Nữ' },
  { value: 'Other', label: 'Khác' },
]

export const STUDENT_STATUS_OPTIONS = [
  { value: 'Active', label: 'Đang ở' },
  { value: 'PendingMoveIn', label: 'Chờ nhận phòng' },
  { value: 'Waiting', label: 'Chờ xếp phòng' },
  { value: 'Pending', label: 'Chờ duyệt' },
  { value: 'Inactive', label: 'Ngừng ở' },
]

export const REGISTRATION_STATUS_OPTIONS = [
  { value: 'Pending', label: 'Chờ duyệt' },
  { value: 'Approved', label: 'Đã duyệt' },
  { value: 'Rejected', label: 'Từ chối' },
]

export const CONTRACT_STATUS_OPTIONS = [
  { value: 'Active', label: 'Hiệu lực' },
  { value: 'Expired', label: 'Hết hạn' },
  { value: 'Cancelled', label: 'Đã hủy' },
]

export const INVOICE_STATUS_OPTIONS = [
  { value: 'Unpaid', label: 'Chưa thanh toán' },
  { value: 'Paid', label: 'Đã thanh toán' },
  { value: 'PartiallyPaid', label: 'Thanh toán một phần' },
  { value: 'Late', label: 'Quá hạn' },
]

export const PAYMENT_METHOD_OPTIONS = [
  { value: 'Cash', label: 'Tiền mặt' },
  { value: 'Transfer', label: 'Chuyển khoản' },
  { value: 'Other', label: 'Khác' },
]

export const ENTITY_CONFIGS = {
  buildings: {
    title: 'Danh sách tòa nhà',
    description: 'Quản lý khu nhà, chính sách giới tính và người phụ trách.',
    columns: [
      ['code', 'Mã'],
      ['name', 'Tên tòa'],
      ['genderPolicy', 'Loại khu'],
      ['numberOfFloors', 'Số tầng'],
      ['roomCount', 'Số phòng'],
      ['currentOccupancy', 'Đang ở'],
      ['totalCapacity', 'Sức chứa'],
    ],
    fields: [
      { name: 'code', label: 'Mã tòa nhà', type: 'text' },
      { name: 'name', label: 'Tên tòa nhà', type: 'text' },
      { name: 'genderPolicy', label: 'Loại khu', type: 'select', options: GENDER_POLICY_OPTIONS },
      { name: 'numberOfFloors', label: 'Số tầng', type: 'number' },
      { name: 'managerName', label: 'Người quản lý', type: 'text' },
      { name: 'description', label: 'Mô tả', type: 'textarea' },
    ],
  },
  rooms: {
    title: 'Danh sách phòng',
    description: 'Theo dõi công suất, sức chứa và tình trạng từng phòng.',
    columns: [
      ['roomNumber', 'Phòng'],
      ['buildingName', 'Tòa nhà'],
      ['floorNumber', 'Tầng'],
      ['roomType', 'Loại phòng'],
      ['capacity', 'Sức chứa'],
      ['currentOccupancy', 'Đang ở'],
      ['availableSlots', 'Còn trống'],
      ['status', 'Trạng thái'],
    ],
    fields: [
      { name: 'roomNumber', label: 'Số phòng', type: 'text' },
      { name: 'buildingId', label: 'Tòa nhà', type: 'lookup', lookup: 'buildings', optionLabel: (item) => `${item.code} - ${item.name}` },
      { name: 'floorNumber', label: 'Tầng', type: 'number' },
      { name: 'roomType', label: 'Loại phòng', type: 'select', options: ROOM_TYPE_OPTIONS },
      { name: 'capacity', label: 'Sức chứa', type: 'number' },
      { name: 'pricePerMonth', label: 'Giá theo tháng', type: 'number' },
      { name: 'status', label: 'Trạng thái', type: 'select', options: ROOM_STATUS_OPTIONS },
    ],
  },
  students: {
    title: 'Hồ sơ sinh viên',
    description: 'Quản lý hồ sơ, liên hệ và tình trạng lưu trú từng sinh viên.',
    columns: [
      ['studentCode', 'MSSV'],
      ['name', 'Họ tên'],
      ['gender', 'Giới tính'],
      ['faculty', 'Khoa'],
      ['className', 'Lớp'],
      ['roomNumber', 'Phòng'],
      ['status', 'Trạng thái'],
    ],
    fields: [
      { name: 'studentCode', label: 'Mã sinh viên', type: 'text' },
      { name: 'name', label: 'Họ tên', type: 'text' },
      { name: 'gender', label: 'Giới tính', type: 'select', options: GENDER_OPTIONS },
      { name: 'dateOfBirth', label: 'Ngày sinh', type: 'date' },
      { name: 'phone', label: 'Số điện thoại', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'faculty', label: 'Khoa', type: 'text' },
      { name: 'className', label: 'Lớp', type: 'text' },
      { name: 'address', label: 'Địa chỉ', type: 'text' },
      { name: 'emergencyContact', label: 'Liên hệ khẩn cấp', type: 'text' },
      { name: 'status', label: 'Trạng thái', type: 'select', options: STUDENT_STATUS_OPTIONS },
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', allowEmpty: true, optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
    ],
  },
  registrations: {
    title: 'Đăng ký nội trú',
    description: 'Xử lý hồ sơ đăng ký, duyệt hoặc từ chối theo quy trình.',
    columns: [
      ['studentCode', 'MSSV'],
      ['studentName', 'Sinh viên'],
      ['roomNumber', 'Phòng yêu cầu'],
      ['registrationDate', 'Ngày đăng ký'],
      ['approvedDate', 'Ngày xử lý'],
      ['status', 'Trạng thái'],
    ],
    fields: [
      { name: 'studentId', label: 'Sinh viên', type: 'lookup', lookup: 'students', optionLabel: (item) => `${item.studentCode} - ${item.name}` },
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'registrationDate', label: 'Ngày đăng ký', type: 'date' },
      { name: 'approvedDate', label: 'Ngày xử lý', type: 'date', allowEmpty: true },
      { name: 'note', label: 'Ghi chú', type: 'textarea' },
      { name: 'status', label: 'Trạng thái', type: 'select', options: REGISTRATION_STATUS_OPTIONS },
    ],
  },
  contracts: {
    title: 'Hợp đồng lưu trú',
    description: 'Theo dõi hợp đồng hiệu lực, hết hạn và các đợt gia hạn.',
    columns: [
      ['contractCode', 'Mã HĐ'],
      ['studentName', 'Sinh viên'],
      ['roomNumber', 'Phòng'],
      ['depositAmount', 'Đặt cọc'],
      ['monthlyFee', 'Phí tháng'],
      ['endDate', 'Hết hạn'],
      ['status', 'Trạng thái'],
    ],
    fields: [
      { name: 'contractCode', label: 'Mã hợp đồng', type: 'text' },
      { name: 'studentId', label: 'Sinh viên', type: 'lookup', lookup: 'students', optionLabel: (item) => `${item.studentCode} - ${item.name}` },
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'depositAmount', label: 'Tiền đặt cọc', type: 'number' },
      { name: 'monthlyFee', label: 'Phí hàng tháng', type: 'number' },
      { name: 'startDate', label: 'Ngày bắt đầu', type: 'date' },
      { name: 'endDate', label: 'Ngày kết thúc', type: 'date' },
      { name: 'status', label: 'Trạng thái', type: 'select', options: CONTRACT_STATUS_OPTIONS },
    ],
  },
  utilities: {
    title: 'Chỉ số điện nước',
    description: 'Quản lý kỳ ghi chỉ số và làm căn cứ tạo công nợ, hóa đơn theo phòng.',
    columns: [
      ['roomNumber', 'Phòng'],
      ['buildingName', 'Tòa nhà'],
      ['billingMonth', 'Kỳ tính'],
      ['electricityUsage', 'Điện tiêu thụ'],
      ['waterUsage', 'Nước tiêu thụ'],
      ['electricityFee', 'Tiền điện'],
      ['waterFee', 'Tiền nước'],
      ['generatedRoomFinanceCount', 'Đã tạo công nợ'],
    ],
    fields: [
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'billingMonth', label: 'Kỳ tính', type: 'date' },
      { name: 'electricityOld', label: 'Điện cũ', type: 'number' },
      { name: 'electricityNew', label: 'Điện mới', type: 'number' },
      { name: 'waterOld', label: 'Nước cũ', type: 'number' },
      { name: 'waterNew', label: 'Nước mới', type: 'number' },
      { name: 'electricityUnitPrice', label: 'Đơn giá điện', type: 'number' },
      { name: 'waterUnitPrice', label: 'Đơn giá nước', type: 'number' },
    ],
  },
  roomFeeProfiles: {
    title: 'Cấu hình phí theo phòng',
    description: 'Thiết lập tiền phòng và các loại phí đi kèm cho từng phòng.',
    columns: [
      ['roomNumber', 'Phòng'],
      ['buildingName', 'Tòa nhà'],
      ['monthlyRoomFee', 'Tiền phòng'],
      ['hygieneFee', 'Phí vệ sinh'],
      ['serviceFee', 'Phí dịch vụ'],
      ['internetFee', 'Phí internet'],
      ['otherFee', 'Phí khác'],
      ['billingCycleDay', 'Ngày chốt'],
    ],
    fields: [
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'monthlyRoomFee', label: 'Tiền phòng', type: 'number' },
      { name: 'electricityUnitPrice', label: 'Đơn giá điện', type: 'number' },
      { name: 'waterUnitPrice', label: 'Đơn giá nước', type: 'number' },
      { name: 'hygieneFee', label: 'Phí vệ sinh', type: 'number' },
      { name: 'serviceFee', label: 'Phí dịch vụ', type: 'number' },
      { name: 'internetFee', label: 'Phí internet', type: 'number' },
      { name: 'otherFee', label: 'Khoản phí khác', type: 'number' },
      { name: 'otherFeeName', label: 'Tên khoản phí khác', type: 'text' },
      { name: 'billingCycleDay', label: 'Ngày chốt thu', type: 'number' },
      { name: 'notes', label: 'Ghi chú', type: 'textarea' },
    ],
  },
  roomFinances: {
    title: 'Công nợ tài chính theo phòng',
    description: 'Theo dõi tiền phòng, điện nước, vệ sinh và trạng thái đã nộp tiền theo từng phòng.',
    columns: [
      ['roomNumber', 'Phòng'],
      ['buildingName', 'Tòa nhà'],
      ['billingMonth', 'Kỳ'],
      ['total', 'Tổng phải thu'],
      ['paidAmount', 'Đã thu'],
      ['remainingAmount', 'Còn lại'],
      ['status', 'Trạng thái'],
      ['dueDate', 'Hạn thu'],
    ],
    fields: [
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'utilityId', label: 'Kỳ điện nước', type: 'lookup', lookup: 'utilities', allowEmpty: true, optionLabel: (item) => `#${item.id} - ${item.billingMonth}` },
      { name: 'billingMonth', label: 'Kỳ công nợ', type: 'date' },
      { name: 'monthlyRoomFee', label: 'Tiền phòng', type: 'number' },
      { name: 'electricityFee', label: 'Tiền điện', type: 'number' },
      { name: 'waterFee', label: 'Tiền nước', type: 'number' },
      { name: 'hygieneFee', label: 'Phí vệ sinh', type: 'number' },
      { name: 'serviceFee', label: 'Phí dịch vụ', type: 'number' },
      { name: 'internetFee', label: 'Phí internet', type: 'number' },
      { name: 'otherFee', label: 'Phí khác', type: 'number' },
      { name: 'paidAmount', label: 'Đã thu', type: 'number' },
      { name: 'dueDate', label: 'Hạn thu', type: 'date' },
      { name: 'paidDate', label: 'Ngày thanh toán', type: 'date', allowEmpty: true },
      { name: 'status', label: 'Trạng thái', type: 'select', options: INVOICE_STATUS_OPTIONS },
      { name: 'paymentMethod', label: 'Hình thức thu', type: 'select', options: PAYMENT_METHOD_OPTIONS, allowEmpty: true },
      { name: 'recordedBy', label: 'Người thu', type: 'text' },
      { name: 'paymentNote', label: 'Ghi chú thu tiền', type: 'textarea' },
    ],
  },
  invoices: {
    title: 'Hóa đơn',
    description: 'Theo dõi công nợ, hạn thu và lịch sử thanh toán của sinh viên.',
    columns: [
      ['invoiceCode', 'Mã HĐ'],
      ['studentName', 'Sinh viên'],
      ['roomNumber', 'Phòng'],
      ['billingMonth', 'Kỳ'],
      ['total', 'Tổng tiền'],
      ['dueDate', 'Hạn thu'],
      ['status', 'Trạng thái'],
    ],
    fields: [
      { name: 'invoiceCode', label: 'Mã hóa đơn', type: 'text' },
      { name: 'studentId', label: 'Sinh viên', type: 'lookup', lookup: 'students', optionLabel: (item) => `${item.studentCode} - ${item.name}` },
      { name: 'roomId', label: 'Phòng', type: 'lookup', lookup: 'rooms', optionLabel: (item) => `${item.roomNumber} (${item.buildingName})` },
      { name: 'utilityId', label: 'Bản ghi điện nước', type: 'lookup', lookup: 'utilities', allowEmpty: true, optionLabel: (item) => `#${item.id} - ${item.billingMonth}` },
      { name: 'roomFee', label: 'Tiền phòng', type: 'number' },
      { name: 'electricityFee', label: 'Tiền điện', type: 'number' },
      { name: 'waterFee', label: 'Tiền nước', type: 'number' },
      { name: 'serviceFee', label: 'Phí dịch vụ tổng hợp', type: 'number' },
      { name: 'billingMonth', label: 'Kỳ hóa đơn', type: 'date' },
      { name: 'dueDate', label: 'Hạn thanh toán', type: 'date' },
      { name: 'paidDate', label: 'Ngày thanh toán', type: 'date', allowEmpty: true },
      { name: 'status', label: 'Trạng thái', type: 'select', options: INVOICE_STATUS_OPTIONS },
    ],
  },
  roles: {
    title: 'Vai trò hệ thống',
    description: 'Phân quyền quản trị, kế toán và điều hành ký túc xá.',
    columns: [
      ['name', 'Tên vai trò'],
      ['description', 'Mô tả'],
    ],
    fields: [
      { name: 'name', label: 'Tên vai trò', type: 'text' },
      { name: 'description', label: 'Mô tả', type: 'textarea' },
    ],
  },
  users: {
    title: 'Tài khoản quản trị',
    description: 'Quản lý tài khoản vận hành, phân quyền và kích hoạt hệ thống.',
    columns: [
      ['username', 'Tài khoản'],
      ['fullName', 'Họ tên'],
      ['email', 'Email'],
      ['roleName', 'Vai trò'],
      ['isActive', 'Kích hoạt'],
    ],
    fields: [
      { name: 'username', label: 'Tên đăng nhập', type: 'text' },
      { name: 'fullName', label: 'Họ tên', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'passwordHash', label: 'Mật khẩu', type: 'text' },
      { name: 'roleId', label: 'Vai trò', type: 'lookup', lookup: 'roles', optionLabel: (item) => item.name },
      { name: 'isActive', label: 'Kích hoạt', type: 'checkbox' },
    ],
  },
}
