import { buildEnumOptions, buildValueLabels } from "./enums";

const currency = new Intl.NumberFormat("vi-VN", {
  style: "currency",
  currency: "VND",
  maximumFractionDigits: 0,
});

export const API_ENDPOINTS = {
  roomCategories: "/api/catalog/room-categories",
  roomZones: "/api/catalog/room-zones",
  paymentMethods: "/api/catalog/payment-methods",
  buildings: "/api/facilities/buildings",
  rooms: "/api/facilities/rooms",
  students: "/api/people/students",
  registrations: "/api/operations/registrations",
  contracts: "/api/operations/contracts",
  utilities: "/api/operations/utilities",
  roomFeeProfiles: "/api/operations/room-fee-profiles",
  roomFinances: "/api/operations/room-finances",
  invoices: "/api/operations/invoices",
  roles: "/api/people/roles",
  users: "/api/people/users",
};

export const NAVIGATION = [
  { key: "overview", path: "/overview", label: "Tổng quan" },
  { key: "catalog", path: "/catalog", label: "Danh mục" },
  { key: "operations", path: "/operations", label: "Điều phối phòng" },
  { key: "facilities", path: "/facilities", label: "Cơ sở vật chất" },
  { key: "students", path: "/students", label: "Sinh viên" },
  { key: "finance", path: "/finance", label: "Tài chính" },
  { key: "admin", path: "/admin", label: "Quản trị" },
];

export const VALUE_LABELS = buildValueLabels();
export const GENDER_POLICY_OPTIONS = buildEnumOptions("genderPolicy");
export const ROOM_TYPE_OPTIONS = buildEnumOptions("roomType");
export const ROOM_STATUS_OPTIONS = buildEnumOptions("roomStatus");
export const GENDER_OPTIONS = buildEnumOptions("gender");
export const STUDENT_STATUS_OPTIONS = buildEnumOptions("studentStatus");
export const REGISTRATION_STATUS_OPTIONS =
  buildEnumOptions("registrationStatus");
export const CONTRACT_STATUS_OPTIONS = buildEnumOptions("contractStatus");
export const INVOICE_STATUS_OPTIONS = buildEnumOptions("invoiceStatus");
export const PAYMENT_METHOD_OPTIONS = buildEnumOptions("paymentMethod");

export const ENTITY_CONFIGS = {
  roomCategories: {
    title: "Danh mục loại phòng",
    description:
      "Tạo trước các loại phòng thực tế như phòng đơn, phòng đôi, giường tầng kèm sức chứa, giá và bộ phí mặc định.",
    columns: [
      ["code", "Mã"],
      ["name", "Loại phòng"],
      ["bedLayout", "Bố trí giường"],
      ["defaultCapacity", "Sức chứa"],
      ["baseMonthlyFee", "Tiền phòng"],
      ["depositAmount", "Tiền cọc"],
      ["serviceFee", "Phí dịch vụ"],
      ["internetFee", "Internet"],
      ["isActive", "Hoạt động"],
    ],
    fields: [
      { name: "code", label: "Mã loại phòng", type: "text" },
      { name: "name", label: "Tên loại phòng", type: "text" },
      { name: "bedLayout", label: "Bố trí giường", type: "text" },
      { name: "defaultCapacity", label: "Sức chứa mặc định", type: "number" },
      { name: "baseMonthlyFee", label: "Tiền phòng mặc định", type: "number" },
      { name: "depositAmount", label: "Tiền cọc", type: "number" },
      { name: "hygieneFee", label: "Phí vệ sinh", type: "number" },
      { name: "serviceFee", label: "Phí dịch vụ", type: "number" },
      { name: "internetFee", label: "Phí internet", type: "number" },
      { name: "electricityUnitPrice", label: "Đơn giá điện", type: "number" },
      { name: "waterUnitPrice", label: "Đơn giá nước", type: "number" },
      {
        name: "description",
        label: "Mô tả",
        type: "textarea",
        allowEmpty: true,
      },
      { name: "isActive", label: "Đang sử dụng", type: "checkbox" },
    ],
  },
  roomZones: {
    title: "Danh mục phân khu phòng",
    description:
      "Chia nhỏ tòa/phòng theo phân khu, tầng, chính sách giới tính và người phụ trách để điều phối sát thực tế.",
    columns: [
      ["code", "Mã"],
      ["name", "Phân khu"],
      ["buildingName", "Tòa nhà"],
      ["genderPolicy", "Chính sách"],
      ["floorFrom", "Từ tầng"],
      ["floorTo", "Đến tầng"],
      ["managerName", "Phụ trách"],
      ["roomCount", "Số phòng"],
      ["isActive", "Hoạt động"],
    ],
    fields: [
      { name: "code", label: "Mã phân khu", type: "text" },
      { name: "name", label: "Tên phân khu", type: "text" },
      {
        name: "buildingId",
        label: "Tòa nhà",
        type: "lookup",
        lookup: "buildings",
        allowEmpty: true,
        optionLabel: (item) => `${item.code} - ${item.name}`,
      },
      {
        name: "genderPolicy",
        label: "Chính sách giới tính",
        type: "select",
        options: GENDER_POLICY_OPTIONS,
      },
      { name: "floorFrom", label: "Từ tầng", type: "number" },
      { name: "floorTo", label: "Đến tầng", type: "number" },
      {
        name: "managerName",
        label: "Người phụ trách",
        type: "lookup",
        lookup: "users",
        allowEmpty: true,
        optionValue: (item) => item.fullName || item.username,
        optionLabel: (item) =>
          `${item.fullName || item.username} (${item.roleName || "User"})`,
      },
      {
        name: "description",
        label: "Mô tả",
        type: "textarea",
        allowEmpty: true,
      },
      { name: "isActive", label: "Đang sử dụng", type: "checkbox" },
    ],
  },
  paymentMethods: {
    title: "Danh mục hình thức thanh toán",
    description:
      "Quản lý tiền mặt, chuyển khoản, POS hoặc các kênh thu khác kèm thông tin tài khoản và phí xử lý.",
    columns: [
      ["code", "Mã"],
      ["name", "Hình thức"],
      ["accountName", "Chủ tài khoản"],
      ["accountNumber", "Số tài khoản"],
      ["bankName", "Ngân hàng"],
      ["processingFee", "Phí xử lý"],
      ["isActive", "Hoạt động"],
    ],
    fields: [
      { name: "code", label: "Mã hình thức", type: "text" },
      { name: "name", label: "Tên hình thức", type: "text" },
      {
        name: "accountName",
        label: "Chủ tài khoản",
        type: "text",
        allowEmpty: true,
      },
      {
        name: "accountNumber",
        label: "Số tài khoản",
        type: "text",
        allowEmpty: true,
      },
      { name: "bankName", label: "Ngân hàng", type: "text", allowEmpty: true },
      { name: "processingFee", label: "Phí xử lý", type: "number" },
      {
        name: "description",
        label: "Mô tả",
        type: "textarea",
        allowEmpty: true,
      },
      { name: "isActive", label: "Đang sử dụng", type: "checkbox" },
    ],
  },
  buildings: {
    title: "Danh sách tòa nhà",
    description: "Quản lý khu nhà, chính sách giới tính và người phụ trách.",
    columns: [
      ["code", "Mã"],
      ["name", "Tên tòa"],
      ["genderPolicy", "Loại khu"],
      ["numberOfFloors", "Số tầng"],
      ["roomCount", "Số phòng"],
      ["currentOccupancy", "Đang ở"],
      ["totalCapacity", "Sức chứa"],
    ],
    fields: [
      { name: "code", label: "Mã tòa nhà", type: "text" },
      { name: "name", label: "Tên tòa nhà", type: "text" },
      {
        name: "genderPolicy",
        label: "Loại khu",
        type: "select",
        options: GENDER_POLICY_OPTIONS,
      },
      { name: "numberOfFloors", label: "Số tầng", type: "number" },
      {
        name: "managerName",
        label: "Người quản lý",
        type: "lookup",
        lookup: "users",
        allowEmpty: true,
        optionValue: (item) => item.fullName || item.username,
        optionLabel: (item) =>
          `${item.fullName || item.username} (${item.roleName || "User"})`,
      },
      {
        name: "description",
        label: "Mô tả",
        type: "textarea",
        allowEmpty: true,
      },
    ],
  },
  rooms: {
    title: "Danh sách phòng",
    description: "Theo dõi công suất, sức chứa và tình trạng từng phòng.",
    columns: [
      ["roomNumber", "Phòng"],
      ["buildingName", "Tòa nhà"],
      ["roomCategoryName", "Loại phòng"],
      ["roomZoneName", "Phân khu"],
      ["floorNumber", "Tầng"],
      ["capacity", "Sức chứa"],
      ["currentOccupancy", "Đang ở"],
      ["availableSlots", "Còn trống"],
      ["status", "Trạng thái"],
    ],
    fields: [
      { name: "roomNumber", label: "Số phòng", type: "text" },
      {
        name: "buildingId",
        label: "Tòa nhà",
        type: "lookup",
        lookup: "buildings",
        optionLabel: (item) => `${item.code} - ${item.name}`,
      },
      {
        name: "roomCategoryId",
        label: "Loại phòng",
        type: "lookup",
        lookup: "roomCategories",
        optionLabel: (item) =>
          `${item.name} - ${currency.format(item.baseMonthlyFee)}`,
      },
      {
        name: "roomZoneId",
        label: "Phân khu",
        type: "lookup",
        lookup: "roomZones",
        allowEmpty: true,
        optionLabel: (item) => `${item.code} - ${item.name}`,
      },
      { name: "floorNumber", label: "Tầng", type: "number" },
      { name: "capacity", label: "Sức chứa", type: "number" },
      { name: "pricePerMonth", label: "Giá theo tháng", type: "number" },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: ROOM_STATUS_OPTIONS,
      },
    ],
  },
  students: {
    title: "Hồ sơ sinh viên",
    description: "Quản lý hồ sơ, liên hệ và tình trạng lưu trú từng sinh viên.",
    columns: [
      ["studentCode", "MSSV"],
      ["name", "Họ tên"],
      ["gender", "Giới tính"],
      ["faculty", "Khoa"],
      ["className", "Lớp"],
      ["accountUsername", "Tài khoản"],
      ["contractWarning", "Hợp đồng"],
      ["status", "Trạng thái"],
    ],
    fields: [
      { name: "studentCode", label: "Mã sinh viên", type: "text" },
      { name: "name", label: "Họ tên", type: "text" },
      {
        name: "gender",
        label: "Giới tính",
        type: "select",
        options: GENDER_OPTIONS,
      },
      { name: "dateOfBirth", label: "Ngày sinh", type: "date" },
      { name: "phone", label: "Số điện thoại", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "faculty", label: "Khoa", type: "text" },
      { name: "className", label: "Lớp", type: "text" },
      { name: "address", label: "Địa chỉ", type: "text" },
      { name: "emergencyContact", label: "Liên hệ khẩn cấp", type: "text" },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: STUDENT_STATUS_OPTIONS,
      },
      {
        name: "accountUsername",
        label: "Tài khoản sinh viên",
        type: "text",
        allowEmpty: true,
        createOnly: true,
      },
      {
        name: "accountPassword",
        label: "Mật khẩu ban đầu",
        type: "password",
        allowEmpty: true,
        createOnly: true,
      },
    ],
  },
  registrations: {
    title: "Đăng ký nội trú",
    description: "Xử lý hồ sơ đăng ký, duyệt hoặc từ chối theo quy trình.",
    columns: [
      ["studentCode", "MSSV"],
      ["studentName", "Sinh viên"],
      ["roomNumber", "Phòng yêu cầu"],
      ["registrationDate", "Ngày đăng ký"],
      ["approvedDate", "Ngày xử lý"],
      ["status", "Trạng thái"],
    ],
    fields: [
      {
        name: "studentId",
        label: "Sinh viên",
        type: "lookup",
        lookup: "students",
        optionLabel: (item) => `${item.studentCode} - ${item.name}`,
      },
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      { name: "registrationDate", label: "Ngày đăng ký", type: "date" },
      { name: "note", label: "Ghi chú", type: "textarea", allowEmpty: true },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: REGISTRATION_STATUS_OPTIONS,
      },
    ],
  },
  contracts: {
    title: "Hợp đồng lưu trú",
    description: "Theo dõi hợp đồng hiệu lực, hết hạn và các đợt gia hạn.",
    columns: [
      ["contractCode", "Mã HĐ"],
      ["studentName", "Sinh viên"],
      ["depositAmount", "Đặt cọc"],
      ["monthlyFee", "Phí tháng"],
      ["endDate", "Hết hạn"],
      ["status", "Trạng thái"],
    ],
    fields: [
      { name: "contractCode", label: "Mã hợp đồng", type: "text" },
      {
        name: "studentId",
        label: "Sinh viên",
        type: "lookup",
        lookup: "students",
        optionLabel: (item) => `${item.studentCode} - ${item.name}`,
      },
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      { name: "depositAmount", label: "Tiền đặt cọc", type: "number" },
      { name: "monthlyFee", label: "Phí hàng tháng", type: "number" },
      { name: "startDate", label: "Ngày bắt đầu", type: "date" },
      { name: "endDate", label: "Ngày kết thúc", type: "date" },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: CONTRACT_STATUS_OPTIONS,
      },
    ],
  },
  utilities: {
    title: "Chỉ số điện nước",
    description:
      "Quản lý kỳ ghi chỉ số và làm căn cứ tạo công nợ, hóa đơn theo phòng.",
    columns: [
      ["roomNumber", "Phòng"],
      ["buildingName", "Tòa nhà"],
      ["billingMonth", "Kỳ tính"],
      ["electricityUsage", "Điện tiêu thụ"],
      ["waterUsage", "Nước tiêu thụ"],
      ["electricityFee", "Tiền điện"],
      ["waterFee", "Tiền nước"],
      ["generatedRoomFinanceCount", "Đã tạo công nợ"],
    ],
    fields: [
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      { name: "billingMonth", label: "Kỳ tính", type: "date" },
      { name: "electricityOld", label: "Điện cũ", type: "number" },
      { name: "electricityNew", label: "Điện mới", type: "number" },
      { name: "waterOld", label: "Nước cũ", type: "number" },
      { name: "waterNew", label: "Nước mới", type: "number" },
      {
        name: "electricityUnitPrice",
        label: "Đơn giá điện / 1 số",
        type: "number",
      },
      { name: "waterUnitPrice", label: "Đơn giá nước / 1 số", type: "number" },
      {
        name: "electricityEvidenceUrl",
        label: "Ảnh minh chứng điện (URL)",
        type: "text",
        allowEmpty: true,
      },
      {
        name: "waterEvidenceUrl",
        label: "Ảnh minh chứng nước (URL)",
        type: "text",
        allowEmpty: true,
      },
    ],
  },
  roomFeeProfiles: {
    title: "Cấu hình phí theo phòng",
    description: "Thiết lập tiền phòng và các loại phí đi kèm cho từng phòng.",
    columns: [
      ["roomNumber", "Phòng"],
      ["buildingName", "Tòa nhà"],
      ["monthlyRoomFee", "Tiền phòng"],
      ["hygieneFee", "Phí vệ sinh"],
      ["serviceFee", "Phí dịch vụ"],
      ["internetFee", "Phí internet"],
      ["otherFee", "Phí khác"],
      ["billingCycleDay", "Ngày chốt"],
    ],
    fields: [
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      { name: "monthlyRoomFee", label: "Tiền phòng", type: "number" },
      { name: "electricityUnitPrice", label: "Đơn giá điện", type: "number" },
      { name: "waterUnitPrice", label: "Đơn giá nước", type: "number" },
      { name: "hygieneFee", label: "Phí vệ sinh", type: "number" },
      { name: "serviceFee", label: "Phí dịch vụ", type: "number" },
      { name: "internetFee", label: "Phí internet", type: "number" },
      { name: "otherFee", label: "Khoản phí khác", type: "number" },
      {
        name: "otherFeeName",
        label: "Tên khoản phí khác",
        type: "text",
        allowEmpty: true,
      },
      { name: "billingCycleDay", label: "Ngày chốt thu", type: "number" },
      { name: "notes", label: "Ghi chú", type: "textarea", allowEmpty: true },
    ],
  },
  roomFinances: {
    title: "Công nợ tài chính theo phòng",
    description:
      "Theo dõi tiền phòng, điện nước, vệ sinh và trạng thái đã nộp tiền theo từng phòng.",
    columns: [
      ["roomNumber", "Phòng"],
      ["buildingName", "Tòa nhà"],
      ["billingMonth", "Kỳ"],
      ["total", "Tổng phải thu"],
      ["paidAmount", "Đã thu"],
      ["remainingAmount", "Còn lại"],
      ["status", "Trạng thái"],
      ["dueDate", "Hạn thu"],
      ["shareCount", "SV chia"],
      ["paidShareCount", "SV nộp"],
    ],
    fields: [
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      {
        name: "utilityId",
        label: "Kỳ điện nước",
        type: "lookup",
        lookup: "utilities",
        allowEmpty: true,
        optionLabel: (item) => `#${item.id} - ${item.billingMonth}`,
      },
      { name: "billingMonth", label: "Kỳ công nợ", type: "date" },
      { name: "monthlyRoomFee", label: "Tiền phòng", type: "number" },
      { name: "electricityFee", label: "Tiền điện", type: "number" },
      { name: "waterFee", label: "Tiền nước", type: "number" },
      { name: "hygieneFee", label: "Phí vệ sinh", type: "number" },
      { name: "serviceFee", label: "Phí dịch vụ", type: "number" },
      { name: "internetFee", label: "Phí internet", type: "number" },
      { name: "otherFee", label: "Phí khác", type: "number" },
      { name: "dueDate", label: "Hạn thu", type: "date" },
      { name: "paidAmount", label: "Đã thu", type: "number", editOnly: true },
      {
        name: "paidDate",
        label: "Ngày thanh toán",
        type: "date",
        allowEmpty: true,
        editOnly: true,
      },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: INVOICE_STATUS_OPTIONS,
        editOnly: true,
      },
      {
        name: "paymentMethod",
        label: "Hình thức thu",
        type: "lookupCode",
        lookup: "paymentMethods",
        allowEmpty: true,
        editOnly: true,
        optionLabel: (item) =>
          `${item.name}${item.processingFee ? ` - phí ${currency.format(item.processingFee)}` : ""}`,
      },
      {
        name: "recordedBy",
        label: "Người thu",
        type: "lookup",
        lookup: "users",
        allowEmpty: true,
        editOnly: true,
        optionValue: (item) => item.fullName || item.username,
        optionLabel: (item) =>
          `${item.fullName || item.username} (${item.roleName || "User"})`,
      },
      {
        name: "paymentNote",
        label: "Ghi chú thu tiền",
        type: "textarea",
        allowEmpty: true,
        editOnly: true,
      },
    ],
  },
  invoices: {
    title: "Hóa đơn",
    description:
      "Theo dõi công nợ, hạn thu và lịch sử thanh toán của sinh viên.",
    columns: [
      ["invoiceCode", "Mã HĐ"],
      ["studentName", "Sinh viên"],
      ["roomNumber", "Phòng"],
      ["billingMonth", "Kỳ"],
      ["total", "Tổng tiền"],
      ["dueDate", "Hạn thu"],
      ["status", "Trạng thái"],
    ],
    fields: [
      { name: "invoiceCode", label: "Mã hóa đơn", type: "text" },
      {
        name: "studentId",
        label: "Sinh viên",
        type: "lookup",
        lookup: "students",
        optionLabel: (item) => `${item.studentCode} - ${item.name}`,
      },
      {
        name: "roomId",
        label: "Phòng",
        type: "lookup",
        lookup: "rooms",
        optionLabel: (item) => `${item.roomNumber} (${item.buildingName})`,
      },
      {
        name: "utilityId",
        label: "Bản ghi điện nước",
        type: "lookup",
        lookup: "utilities",
        allowEmpty: true,
        optionLabel: (item) => `#${item.id} - ${item.billingMonth}`,
      },
      { name: "roomFee", label: "Tiền phòng", type: "number" },
      { name: "electricityFee", label: "Tiền điện", type: "number" },
      { name: "waterFee", label: "Tiền nước", type: "number" },
      { name: "serviceFee", label: "Phí dịch vụ tổng hợp", type: "number" },
      { name: "billingMonth", label: "Kỳ hóa đơn", type: "date" },
      { name: "dueDate", label: "Hạn thanh toán", type: "date" },
      {
        name: "paidDate",
        label: "Ngày thanh toán",
        type: "date",
        allowEmpty: true,
      },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        options: INVOICE_STATUS_OPTIONS,
      },
    ],
  },
  roles: {
    title: "Vai trò hệ thống",
    description: "Phân quyền quản trị, kế toán và điều hành ký túc xá.",
    columns: [
      ["name", "Tên vai trò"],
      ["description", "Mô tả"],
    ],
    fields: [
      { name: "name", label: "Tên vai trò", type: "text" },
      {
        name: "description",
        label: "Mô tả",
        type: "textarea",
        allowEmpty: true,
      },
    ],
  },
  users: {
    title: "Tài khoản quản trị",
    description:
      "Quản lý tài khoản vận hành, phân quyền và kích hoạt hệ thống.",
    columns: [
      ["username", "Tài khoản"],
      ["fullName", "Họ tên"],
      ["email", "Email"],
      ["roleName", "Vai trò"],
      ["isActive", "Kích hoạt"],
    ],
    fields: [
      { name: "username", label: "Tên đăng nhập", type: "text" },
      { name: "fullName", label: "Họ tên", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "passwordHash", label: "Mật khẩu", type: "text" },
      {
        name: "roleId",
        label: "Vai trò",
        type: "lookup",
        lookup: "roles",
        optionLabel: (item) => item.name,
      },
      { name: "isActive", label: "Kích hoạt", type: "checkbox" },
    ],
  },
};
